[FIX] revision load testing

diff --git a/.github/workflows/k6-load-test.yml b/.github/workflows/k6-load-test.yml
--- a/.github/workflows/k6-load-test.yml
+++ b/.github/workflows/k6-load-test.yml
@@ -29,11 +29,12 @@ jobs:
         run: |
           echo "Starting Fixed Load Test..."
           mkdir -p backend/tests/load
-          k6 run backend/tests/load/upload-inv-fixed-load.mjs | tee backend/tests/load/fixed-load-test.log || echo "Fixed Load Test failed!"
+          k6 run -e LOAD_CLIENT_ID=${{ secrets.LOAD_CLIENT_ID }} -e LOAD_CLIENT_SECRET=${{ secrets.LOAD_CLIENT_SECRET }} backend/tests/load/upload-inv-fixed-load.mjs | tee backend/tests/load/fixed-load-test.log || echo "Fixed Load Test failed!"
           echo "Fixed Load Test completed."
 
       - name: Run Load Test - Ramping Load
         run: |
           echo "Starting Ramping Load Test..."
-          k6 run backend/tests/load/upload-inv-ramping-load.mjs | tee backend/tests/load/ramping-load-test.log || echo "Ramping Load Test failed!"
+          k6 run -e LOAD_CLIENT_ID=${{ secrets.LOAD_CLIENT_ID }} -e LOAD_CLIENT_SECRET=${{ secrets.LOAD_CLIENT_SECRET }} backend/tests/load/upload-inv-ramping-load.mjs | tee backend/tests/load/ramping-load-test.log || echo "Ramping Load Test failed!"
           echo "Ramping Load Test completed."
+
